# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Batcher < Formula
  desc "batcher does concurrent mass updates and deletes in a database-friendly way"
  homepage ""
  version "0.10.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/SpokeyWheeler/batcher/releases/download/v0.10.7/batcher_0.10.7_Darwin_x86_64.tar.gz"
    sha256 "fc805a7f610de2d1927c2591d935212d2d0508c67a1b023f0caea90477c1192c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/SpokeyWheeler/batcher/releases/download/v0.10.7/batcher_0.10.7_Linux_x86_64.tar.gz"
    sha256 "0372647be2f1976123a94fac63ea2414d0b109eace84cabe815711308e3a7d2a"
  end

  def install
    bin.install "batcher"
  end

  def caveats; <<~EOS
    Execute 'batcher help' to get started
  EOS
  end

  test do
    system "#{bin}/batcher version"
  end
end
