# This file was generated by GoReleaser. DO NOT EDIT.
class Batcher < Formula
  desc "batcher does mass database updates and deletes in a database-friendly, concurrent manner"
  homepage ""
  version "0.6.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/SpokeyWheeler/batcher/releases/download/v0.6.4/batcher_0.6.4_Darwin_x86_64.tar.gz"
    sha256 "b237766466171bf987015912642311a170ecbff824dc0c79b9c7bbf582513250"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/SpokeyWheeler/batcher/releases/download/v0.6.4/batcher_0.6.4_Linux_x86_64.tar.gz"
      sha256 "6efc9b6ddbabe279f2c0acdf6564f23e5641964b0f68109b5f252637a8bcf064"
    end
  end

  def install
    bin.install "batcher"
  end

  def caveats; <<~EOS
    Execute 'batcher help' to get started
  EOS
  end

  test do
    system "#{bin}/batcher version"
  end
end
